services:
  - type: web
    name: nearby-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/nearby-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: nearby-postgres
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: nearby-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nearby-postgres
          property: password

databases:
  - name: nearby-postgres
    databaseName: nearby_db
    user: nearby_user
    plan: free 